name: Publish Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # Ensure we have write permissions for packages
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      # Build first
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Publish to npm
      - name: Setup Node.js for npm publishing
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish to GitHub Packages - Fixed approach
      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Publish to GitHub Packages
        run: |
          # Make sure repository field matches GitHub's requirements
          if ! grep -q '"repository":' package.json; then
            echo "Adding repository field to package.json"
            # Use jq to add the repository field if missing
            jq '.repository = {"type": "git", "url": "git+https://github.com/aashari/boilerplate-npm-package.git"}' package.json > package.json.tmp
            mv package.json.tmp package.json
          fi
          
          # Publish package to GitHub Packages
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 