name: Publish Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write # Need this for OIDC authentication
    steps:
      - uses: actions/checkout@v4
      
      # Build first
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Publish to npm
      - name: Setup Node.js for npm publishing
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish to GitHub Packages
      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@aashari'

      - name: Publish to GitHub Packages
        run: |
          # Create temporary .npmrc specifically for GitHub Packages
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
          echo "@aashari:registry=https://npm.pkg.github.com/" >> .npmrc
          
          # Debug info (no secrets)
          echo "Repository: aashari/boilerplate-npm-package"
          echo "Package name: @aashari/boilerplate-npm-package"
          
          # Publish with verbose output
          npm publish --access public --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 