name: Publish Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js for npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@aashari'

      - name: Publish to GitHub Packages
        run: |
          # Update package.json temporarily for GitHub Packages
          cp package.json package.json.backup
          sed -i 's|"registry": "https://registry.npmjs.org/"|"registry": "https://npm.pkg.github.com/"|g' package.json
          npm publish
          # Restore the original package.json
          mv package.json.backup package.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 